export const ITEMS = [
  {
    id: 'rbpi1961',
    name: 'Hamlin Rizzetti',
    email: 'hrizzettib@timesonline.co.uk',
    status: 'active',
    key: 12,
  },
  {
    id: 'gkqq4766',
    name: 'Gage Seer',
    email: 'gseerc@shutterfly.com',
    status: 'active',
    key: 13,
  },
  {
    id: 'hggz1620',
    name: 'Fanchette Wickstead',
    email: 'fwicksteadd@unesco.org',
    status: 'inactive',
    key: 14,
  },
  {
    id: 'hebh7597',
    name: 'Wheeler Graffham',
    email: 'wgraffhame@umich.edu',
    status: 'active',
    key: 15,
  },
  {
    id: 'rvtz2669',
    name: 'Samson Faint',
    email: 'sfaintf@ibm.com',
    status: 'active',
    key: 16,
  },
  {
    id: 'yukq1532',
    name: 'Blondie Pauli',
    email: 'bpaulig@odnoklassniki.ru',
    status: 'inactive',
    key: 17,
  },
  {
    id: 'vtow7077',
    name: 'Edeline Whicher',
    email: 'ewhicherh@123-reg.co.uk',
    status: 'inactive',
    key: 18,
  },
  {
    id: 'yelu9558',
    name: 'Elene Jallin',
    email: 'ejallini@shareasale.com',
    status: 'inactive',
    key: 19,
  },
  {
    id: 'upqq9698',
    name: 'Kerstin Ripsher',
    email: 'kripsherj@boston.com',
    status: 'inactive',
    key: 20,
  },
  {
    id: 'mxbk2971',
    name: 'Kaela Deedes',
    email: 'kdeedesk@reverbnation.com',
    status: 'inactive',
    key: 21,
  },
  {
    id: 'bvnk6864',
    name: 'Dyane Laurenceau',
    email: 'dlaurenceaul@wp.com',
    status: 'inactive',
    key: 22,
  },
  {
    id: 'cbvr4104',
    name: 'Grazia Regus',
    email: 'gregusm@accuweather.com',
    status: 'inactive',
    key: 23,
  },
  {
    id: 'mlan6020',
    name: 'Rosalynd Rousell',
    email: 'rrouselln@mapy.cz',
    status: 'inactive',
    key: 24,
  },
  {
    id: 'nqyf7969',
    name: 'Fayre Vennard',
    email: 'fvennardo@delicious.com',
    status: 'active',
    key: 25,
  },
  {
    id: 'dvoo8604',
    name: 'Jacklin Ivatt',
    email: 'jivattp@google.es',
    status: 'inactive',
    key: 26,
  },
  {
    id: 'abwq8671',
    name: 'Hieronymus Snodden',
    email: 'hsnoddenq@constantcontact.com',
    status: 'inactive',
    key: 27,
  },
  {
    id: 'nltw4837',
    name: 'Ruthe Veazey',
    email: 'rveazeyr@sitemeter.com',
    status: 'active',
    key: 28,
  },
  {
    id: 'jjej5358',
    name: 'Kristien Whiteley',
    email: 'kwhiteleys@live.com',
    status: 'active',
    key: 29,
  },
  {
    id: 'rgrs3003',
    name: 'Husein Lyngsted',
    email: 'hlyngstedt@hatena.ne.jp',
    status: 'active',
    key: 30,
  },
];
export const COLUMNS = [
  {
    title: 'ID',
    dataIndex: 'id',
  },
  {
    title: 'Name',
    dataIndex: 'name',
  },
  {
    title: 'E-mail',
    dataIndex: 'email',
  },
];
export const DEFAULT_ROW_SIZE = 5;